version: "3"

volumes:
  local_postgres_data: { }

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - djangonetwork
  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: django
    depends_on:
      - postgres
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
    env_file:
      - ./.envs/.django
    networks:
      - djangonetwork
  celery-beat:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: celery -A myapp.tasks beat -l INFO
    volumes:
      - ./src:/src
    env_file:
      - ./.envs/.django
    depends_on:
      - redis
    networks:
      - djangonetwork
  postgres:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    container_name: postgres
    env_file:
      - ./.envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    networks:
      - djangonetwork
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge